services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-erp_db}
    ports:
      - "${DB_PORT_EXPOSED:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - erp_network

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT_EXPOSED:-3001}:${PORT:-3000}"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-erp_db}
      DB_PORT: ${DB_PORT:-5432}
      PORT: ${PORT:-3000}
      ALERT_EMAIL: ${ALERT_EMAIL:-[EMAIL_ADDRESS]}
      ALERT_EMAIL_PASSWORD: ${ALERT_EMAIL_PASSWORD:-vcctxwtqkazbgwjm}
    volumes:
      - ./backend:/app
      - /app/node_modules
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - erp_network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT_EXPOSED:-5180}:${FRONTEND_PORT_EXPOSED:-5180}"
    environment:
      VITE_PORT: ${FRONTEND_PORT_EXPOSED:-5180}
      VITE_API_URL: http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - erp_network
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  erp_network:
    driver: bridge